# Generated by Django 3.2 on 2023-12-31 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('flight_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('from_date', models.DateTimeField()),
                ('arrived_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.CharField(max_length=20)),
                ('from_location', models.CharField(max_length=20)),
                ('avilable_seat', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='guest',
            fields=[
                ('name', models.TextField()),
                ('identify_card', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=12)),
                ('sex', models.CharField(max_length=8)),
                ('work', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='root_user',
            fields=[
                ('account', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('work', models.CharField(max_length=20)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Travel_agencies',
            fields=[
                ('travel_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='reserve_tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_ticket', models.BooleanField()),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flight')),
                ('identify_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.guest')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='travel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.travel_agencies'),
        ),
    ]
